
FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt

RUN python3 -m pip install --no-cache-dir --upgrade -r requirements.txt

COPY ./ .

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "1"]

# TODO: might need params --ws websockets ?

# buildable locally from repo root as working directory with
# docker build -f deployment/Dockerfile -t myapp .
# then starting a container with
# docker run -p 127.0.0.1:80:8080/tcp myapp
# now service accessible at 127.0.0.1/docs
